<div class="seconnecter">
	<div class="container">
	    <div class="row centered-form">
	        <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
	        	<div class="panel panel-default">
	        		<div class="panel-heading">
				    	<h3 class="panel-title">Je me connecte à mon compte</h3>
				 		</div>
				 		<div class="panel-body">
					    	<form method="post" role="form">
								<div><?=$error?></div>
					    		<div class="row">
					    			<div class="col-xs-6 col-sm-6 col-md-6">
					    				<div class="form-group">
					                		<input type="text" name="login" id="first_name" class="form-control input-sm" placeholder="Login">
					    				</div>
					    			</div>
					    		</div>
					    		<div class="row">
					    			<div class="col-xs-6 col-sm-6 col-md-6">
					    				<div class="form-group">
					    					<input type="password" name="password" id="password" class="form-control input-sm" placeholder="Mot de passe">
					    				</div>
					    			</div>
					    		</div>
					    		<div class="meconnecter">
		                                <button id="singlebutton" value="login" type="submit" name="action" class="btn btn-info btn-block">Je me connecte</button>
		                           </div>
					    	</form>
				    	</div>
		    	</div>
	    	</div>
	    </div>
	</div>
</div>