<div class="panel-footer">
    <div class="input-group">
		<form method="post">
        		<input id="btn-input" type="text" name="content" class="form-control input-sm  js_in" placeholder="Type your message here..." />

         		<span class="input-group-btn">
            		<button class="btn btn-warning btn-sm" name="action" id="btn-chat" value="edit">Envoyer</button>
       		 	</span>
    	</form>
    </div>
</div>