<li class="left clearfix">
    <div class="chat-body clearfix">
        <div class="header">
             <strong class="primary-font"><?=$message->getIdUser()?></strong> <small class="pull-right text-muted">
                <span class="glyphicon glyphicon-time"></span><?=$message->getDate()?></small>
        </div>
        <p>
            <?=$message->getContent()?>
        </p>
    </div>
</li>